#!/bin/bash
#About this script
clear
echo -e ""
echo -e "  ======================="
echo -e "  |   Script by xShin   |"
echo -e "  -----------------------"
echo -e ""
echo -e "  =============="
echo -e "  |   Author   |"
echo -e "  --------------"
echo -e "  Klekai"
echo -e "  Angristan"
echo -e "  Potatonc"
echo -e ""
echo -e "  ================="
echo -e "  |   Thanks to   |"
echo -e "  -----------------"
echo -e "  Stuckoverflow"
echo -e "  Github"
echo -e "  Potatonc"
echo -e "  etc"
echo -e ""
echo -e "  ================================================"
echo -e "  |   Script Menu Version : 0.1 (Beta Version)   |"
echo -e "  ------------------------------------------------"
echo -e ""
