#!/bin/bash
#About this script
clear
echo -e ""
echo -e "================="
echo -e "|   Created By  |"
echo -e "-----------------"
echo -e "- xShin"
echo -e ""
echo -e "================="
echo -e "|   Thanks To   |"
echo -e "-----------------"
echo -e "- Stuckoverflow"
echo -e "- Github"
echo -e "- Klekai"
echo -e "- Angristan"
echo -e "- Potatonc"
echo -e "- etc"
echo -e "- And u"
echo -e ""
echo -e "=============================="
echo -e "|   Script Version : V.1.2   |"
echo -e "------------------------------"
echo -e ""
