#!/bin/bash
#Menu Section
clear
echo -e ""
echo -e ""
echo -e "   ================="
echo -e "   |   Main Menu   |"
echo -e "   -----------------"
echo -e ""
echo -e "   $ menu               MENAMPILKAN MAIN MENU"
echo -e "   $ usernew            MEMBUAT AKUN SSH & OpenVPN BARU"
echo -e "   $ trial              MEMBUAT AKUN SSH & OpenVPN PERCOBAAN"
echo -e "   $ delete             MENGHAPUS AKUN SSH & OpenVPN"
echo -e "   $ cek                MENGECEK AKUN SSH YANG AKTIF"
echo -e "   $ member             MENAMPILKAN SEMUA AKUN SSH & OpenVPN"
echo -e "   $ onkill             MENGAKTIFKAN FITUR AUTO KILL MULTI LOGIN"
echo -e "   $ offkill            MENONAKTIFKAN FITUR AUTO KILL MULTI LOGIN"
echo -e "   $ live               CEK LIVE BANDWIDTH"
echo -e "   $ restart            RESTART SSH & VPN + SQUID PROXY + PORT DROPBEAR"
echo -e "   $ reboot             REBOOT VPS"
echo -e "   $ speedtest          TEST SPEED VPS"
echo -e "   $ perpanjang         PERPANJANG AKUN SSH & OpenVPN"
echo -e "   $ cekmemory          MENAMPILKAN SISA RAM"
echo -e "   $ cekport            CEK PORT OPENSSH / DROPBEAR / SSL / OpenVPN / SQUID"
echo -e "   $ customport         CUSTOM PORT OPENSSH / DROPBEAR"
echo -e "   $ userlimit 1        LIMIT MAX LOGIN 1 ( TIDAK AUTO )"
echo -e "   $ userlimit 2        LIMIT MAX LOGIN 2 ( TIDAK AUTO )"
echo -e "   $ limit 1            LIMIT MAX LOGIN 1 ( AUTO )"
echo -e "   $ limit 2            LIMIT MAX LOGIN 2 ( AUTO )"
echo -e "   $ limit stop         STOP LIMIT 1 & 2"
echo -e "   $ limit cek          MELIHAT LOG AKUN YANG DI LIMIT"
echo -e "   $ limit reset        MERESET LOG / MENGHAPUS SEMUA LOG"
echo -e "   $ info               MENAMPILKAN INFORMASI SISTEM VPS"
echo -e "   $ about              MENAMPILKAN MENGENAI SCRIPT INI"
echo -e "   $ exit               LOGOUT / KELUAR"
echo -e ""