#!/bin/bash
#Menu Section
echo -e ""
echo -e "   ================="
echo -e "   |   Main Menu   |"
echo -e "   -----------------"
echo -e ""
echo -e "   ~ menu               MENAMPILKAN MAIN MENU"
echo -e "   ~ usernew            MEMBUAT AKUN SSH & OpenVPN BARU"
echo -e "   ~ trial              MEMBUAT AKUN SSH & OpenVPN PERCOBAAN"
echo -e "   ~ delete             MENGHAPUS AKUN SSH & OpenVPN"
echo -e "   ~ cek                MENGECEK AKUN SSH YANG AKTIF"
echo -e "   ~ member             MENAMPILKAN SEMUA AKUN SSH & OpenVPN"
echo -e "   ~ live               CEK LIVE BANDWIDTH"
echo -e "   ~ restart            RESTART SSH & VPN + SQUID PROXY + PORT DROPBEAR"
echo -e "   ~ reboot             REBOOT VPS"
echo -e "   ~ speedtest          TEST SPEED VPS"
echo -e "   ~ cekmemory          MENAMPILKAN SISA RAM"
echo -e "   ~ cekport            CEK PORT OPENSSH / DROPBEAR / SSL / OpenVPN / SQUID / NGINX"
echo -e "   ~ statport           CEK STATUS PORT OPENSSH / DROPBEAR / SSL / OpenVPN / SQUID / NGINX"
echo -e "   ~ update             MELIHAT INFO MENGENAI NEW VERSION"
echo -e "   ~ contact            KONTAK PEMBUAT SCRIPT INI"
echo -e "   ~ info               MENAMPILKAN INFORMASI SISTEM VPS"
echo -e "   ~ about              MENAMPILKAN MENGENAI SCRIPT INI"
echo -e ""