#!/bin/bash
#Port Output
echo -e ""
echo -e "Informasi Port"
echo -e ""
echo -e "==============="
echo -e "|   OpenSSH   |"
echo -e "---------------"
echo -e ""
echo -e "* 22"
echo -e "* 444"
echo -e ""
echo -e "================"
echo -e "|   Dropbear   |"
echo -e "----------------"
echo -e ""
echo -e "* 143"
echo -e "* 80"
echo -e "* 236"
echo -e ""
echo -e "==============="
echo -e "|   Stunnel   |"
echo -e "---------------"
echo -e ""
echo -e "* 443"
echo -e ""
echo -e "==============="
echo -e "|   OpenVPN   |"
echo -e "---------------"
echo -e ""
echo -e "Port TCP : * 1194"
echo -e "Port SSL : * 2905"
echo -e "           * 9443"
echo -e "Port UDP : * 25000"
echo -e ""