#!/bin/bash
#Success Output
echo -e ""
echo -e "   TERIMA KASIH TELAH MENGGUNAKAN SCRIPT INI, UNTUK DONASI BISA KE"
echo -e ""
echo -e "   ======================================================"
echo -e "   |                                                    |"
echo -e "   | DANA    = +62 896 3736 9606 ( Arman Dwi Pangestu ) |"
echo -e "   | LinkAja = +62 896 3736 9606 ( Arman Dwi Pangestu ) |"
echo -e "   | OVO     = +62 896 3736 9606 ( Arman Dwi Pangestu ) |"
echo -e "   |                                                    |"
echo -e "   ======================================================"
echo -e ""
echo -e "   ATAU CHAT KONTAK AUTHOR DENGAN MENGETIKKAN 'contact' "
echo -e ""
echo -e "   ==========================="
echo -e "   | ---! Version V.1.2 !--- |"
echo -e "   ==========================="
echo -e ""